services:
  - type: web
    name: florrie-reminder
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: ONESIGNAL_API_KEY
        sync: false
